### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by omkarchittar** [omkarchittar/smarter-university-system#1]
Identifying tasks and organizing them. 
These tasks serve as guidance for the team members through the project and as a progress indicator.

In this part of the project, we will plan the tasks associated with the project. We will utilize the GitHub task-tracking capabilities to create different types of issues. As we progress through the project, we will update the status of issues. The creation of issues and their maintenance are split up into two separate tasks.

**Comment by Sarthak-kiloray** [comment]
Closing this since we have completed both the parts:
1) creating Github issues part
2) create and maintain the board
