### ISSUE TITLE
Information Gathering - Lokesh Bharath

### ISSUE THREAD

**Issue by omkarchittar** [omkarchittar/smarter-university-system#13]
Task for #10 

Gathering information from the project document and the Appendix section

**Comment by Lokesh-Bharath** [comment]
Basic Functional Requirements - Administrator

As an Administrator, I should be able to check on the list of all courses
As an Administrator, I should be able to see number of students enrolled in each course
As an Administrator, I should be able to maximum number of students allowed in each course
As an Administrator, I should receive a mail if a course is 80% or more full
As an Administrator, I should be able to add to a class
As an Administrator, I should be able to remove students from a class
As an Administrator, I should receive and be able to validate student's enrollment requests.
As an Administrator, I should be able to find name, email and education of each instructor
As an Administrator, I should be able to view all the courses an instructor has taught
