### ISSUE TITLE
Information Gathering - Deeksha

### ISSUE THREAD

**Issue by omkarchittar** [omkarchittar/smarter-university-system#15]
Task for #10 

Gathering information from the project document and the Appendix section

**Comment by deeksha-2825** [comment]
Requirements for the project:
1. Student should be able to sign up for the classes on availability.
2. Should display location information of the classes.
3. Should be able to join classes via video capabilities if it is remote
4. Display classes that has not attended by the student as soon as login
5. Display the identifier, title of the class, name of the lecturer and link to the syllabus(along with date and topic)
6. Instructor should have the option to modify the page during the semester.
7. Needs to update the student count if a student signs up for the course.
8. Administrators should be able to add or remove the students
9. Approvals regarding the enrollment request
10. Administrators should be able to find information about the instructor
11. Instructor should be access the list of students.
12. Team assignment for projects 
13. SUS to be the primary database for grades. 
14. Enter grade to the system.
15. Display the low, high and mean grade to the instructor and TA.
16. Students should be able to see all the grades they have received throughout the semester.
