### ISSUE TITLE
Sync up on overall priorities - Team

### ISSUE THREAD

**Issue by nodeicode** [omkarchittar/smarter-university-system#29]

**Comment by deeksha-2825** [comment]
Final priorities were finalized over a meeting

**Comment by deeksha-2825** [comment]
https://docs.google.com/spreadsheets/d/1siJq2NFvHjECc14flo1TM3u1jqYi0bVVDr7OCb7iEcc/edit#gid=1515384822

Individual priorities, Overall priority has been given in the above link and also it has been submitted under the deliverables
